/*
 * adc_program.c
 *
 *  Created on: 20 Oct 2023
 *      Author: Me
 */

#include "../../MCAL/03-ADC/ADC_INTERFACE.h"
#include "../../MCAL/03-ADC/ADC_CONFIG.h"
#include"../../MCAL/03-ADC/ADC_PRIVATE.h"
#include "../../MCAL/01-DIO/DIO_INTERFACE.h"


void ADC_void_Intilize(void){
////////////////////
	DIO_voidSetPinDirection(DIO_u8PORTA,DIO_u8PIN0,DIO_u8PININPUT);
	DIO_voidSetPinDirection(DIO_u8PORTA,DIO_u8PIN7,DIO_u8PININPUT);
	/*REFERANCE SELECTION*/
#if ADC_U8REF_VOLT==ARREF_REF
	CLR_BIT(ADMUX,ADMUX_REFS1);
	CLR_BIT(ADMUX,ADMUX_REFS0);
#elif ADC_U8REF_VOLT==AVCC_REF
	/////////////////////
	/*AVC REFRANCE*/
	SET_BIT(ADMUX,ADMUX_REFS0);
	CLR_BIT(ADMUX,ADMUX_REFS1);
#elif ADC_U8REF_VOLT==INTERRUPT_256VOLT
	SET_BIT(ADMUX,ADMUX_REFS0);
	SET_BIT(ADMUX,ADMUX_REFS1);
#else #error
#endif
	///////////
	/*ADC RESOLUTION*/
#if ADC_RESOLUTION==EIGHT_BITS
	//ACTIVATE LEFT ADJUSTED
	SET_BIT(ADMUX,ADMUX_ADLAR);
#elif 	ADC_RESOLUTION==TEN_BITS
	CLR_BIT(ADMUX,ADMUX_ADLAR);
#else #error
#endif
	///////////////
	/*ADC INTERNAL INTERRUPT*/
#if ADC_U8INTERRUPT==DISABLED
	//ACTIVATE LEFT ADJUSTED
	CLR_BIT(ADCSRA,ADCSRA_ADIE);
#elif 	ADC_U8INTERRUPT==ENABLED
	SET_BIT(ADCSRA,ADCSRA_ADIE);
#else #error
#endif

	//SET_BIT(ADCSRA,ADCSRA_ADIE);  //INTERRUPT
	// SET_BIT(ADCSRA,ADCSRA_ADIF);  //INTERRUPT
	//SPEED (PRESCALER) 7 OPTIONm1
	//SET_BIT(ADCSRA,ADCSRA_ADPS0);
	//SET_BIT(ADCSRA,ADCSRA_ADPS1);
	//SET_BIT(ADCSRA,ADCSRA_ADPS2);
	//PRESCALER
#ifdef ADC_PRESACLER
#if ADC_PRESACLER==ADC_DIV_BY_2
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_4
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_8
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_16
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_32
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_64
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#elif ADC_PRESACLER==ADC_DIV_BY_128
	ADCSRA = ADCSRA & ADC_PRES_MUSK;
	ADCSRA = ADCSRA | ADC_PRESACLER;
#endif
#else #error
#endif
  //OTHER PRESCALER BY BIT MASKING
	/*
	 *
	 */

	//timer0
	SET_BIT(SFIOR,SFIOR_ADTS2);
	CLR_BIT(SFIOR,SFIOR_ADTS1);
	CLR_BIT(SFIOR,SFIOR_ADTS0);
	//ADC ENABLE IN END
	SET_BIT(ADCSRA,ADCSRA_ADEN);
}
uint32 ADC_u32_Get_CHannel_Reading(uint8 Copy_u8Channel){

	/* SINGLEENDED */
	ADMUX = ADMUX & ADC_CHANNEL_MUSK;
	ADMUX = ADMUX | Copy_u8Channel;
	//START CONVERTION
	SET_BIT(ADCSRA,ADCSRA_ADSC);
	while((GET_BIT(ADCSRA,ADCSRA_ADIF))==0){};
	/*ADC FLAG*/
	SET_BIT(ADCSRA,ADCSRA_ADIF);
	/*ADC RESOLUTION*/
	#if ADC_RESOLUTION==EIGHT_BITS
		//ACTIVATE LEFT ADJUSTED
		return ADCH;
	#elif 	ADC_RESOLUTION==TEN_BITS
		return ADC;
	#else #error
	#endif
		/* ADC ENABLE */
		SET_BIT(ADCSRA,ADCSRA_ADEN);
}
uint8 ADC_u8_Start_Convertion(uint8 Copy_u8Channel_number){


	ADCSRA = ADCSRA & ADC_CHANNEL_MUSK;
	ADCSRA = ADCSRA | ADC_CHANNEL_A0;

	//START CONVERTION
	SET_BIT(ADCSRA,ADCSRA_ADSC);
	//WAIT FLAG POLLING
	while((GET_BIT(ADCSRA,ADCSRA_ADIF))==0){

	}
	return ADCH;
}
